# A new style of makefile using pmake or the default make of the userland from
# the BSD world
#
# this Makefile take care about the build of the test program to the simple
# queue implementation

PROG_CXX = mfila
SRCS += ../elem_simples/*.cpp ../lista_simples/*.cpp ../fila/*.cpp main_fila.cpp
CFLAGS += -I../elem_base -I../lista_base -I../fila
MAN =

.include <bsd.prog.mk>

