# A new style of makefile using pmake or the default make of the userland from
# the BSD world
#
# this is the top-most Makefile, and each of the subidrs listed here must have
# one Makefile including the bsd.prog.mk


SUBDIR = fila_prog filap_prog

.include <bsd.subdir.mk>
